package vista;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuActualizarCompania = new javax.swing.JMenu();
        menuConsultarUno = new javax.swing.JMenuItem();
        menuConsultarTodos = new javax.swing.JMenuItem();
        menuEliminarCompania = new javax.swing.JMenuItem();
        menuInsertarCompania = new javax.swing.JMenuItem();
        menuActualizarCompa = new javax.swing.JMenuItem();
        Artista = new javax.swing.JMenu();
        ArtistaConsultarTodos = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuActualizarCompania.setText("Compañía");

        menuConsultarUno.setText("Consultar");
        menuConsultarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarUnoActionPerformed(evt);
            }
        });
        menuActualizarCompania.add(menuConsultarUno);

        menuConsultarTodos.setText("Consultar Todos");
        menuConsultarTodos.setToolTipText("");
        menuConsultarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarTodosActionPerformed(evt);
            }
        });
        menuActualizarCompania.add(menuConsultarTodos);

        menuEliminarCompania.setText("Eliminar Compañía");
        menuEliminarCompania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarCompaniaActionPerformed(evt);
            }
        });
        menuActualizarCompania.add(menuEliminarCompania);

        menuInsertarCompania.setText("Insertar Compañía");
        menuInsertarCompania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInsertarCompaniaActionPerformed(evt);
            }
        });
        menuActualizarCompania.add(menuInsertarCompania);

        menuActualizarCompa.setText("Actualizar Compañía");
        menuActualizarCompa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActualizarCompaActionPerformed(evt);
            }
        });
        menuActualizarCompania.add(menuActualizarCompa);

        menuBar.add(menuActualizarCompania);

        Artista.setText("Artista");

        ArtistaConsultarTodos.setText("Consultar todos");
        ArtistaConsultarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArtistaConsultarTodosActionPerformed(evt);
            }
        });
        Artista.add(ArtistaConsultarTodos);

        menuBar.add(Artista);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuConsultarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarUnoActionPerformed
        if (fomularioConsultaUno == null || fomularioConsultaUno.isClosed()) {
            fomularioConsultaUno = new ConsultaCompania();
            escritorio.add(fomularioConsultaUno);
            fomularioConsultaUno.setVisible(true);
        }
    }//GEN-LAST:event_menuConsultarUnoActionPerformed

    private void menuConsultarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarTodosActionPerformed
        if (formularioConsultaTodosCompanias == null || formularioConsultaTodosCompanias.isClosed()) {
            formularioConsultaTodosCompanias = new ConsultaTodosCompanias();
            escritorio.add(formularioConsultaTodosCompanias);
            formularioConsultaTodosCompanias.setVisible(true);
        }
    }//GEN-LAST:event_menuConsultarTodosActionPerformed


    private void menuEliminarCompaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarCompaniaActionPerformed
        if (eliminarCompania == null || eliminarCompania.isClosed()) {
            eliminarCompania = new EliminarCompania();
            escritorio.add(eliminarCompania);
            eliminarCompania.setVisible(true);
        }
    }//GEN-LAST:event_menuEliminarCompaniaActionPerformed

    private void menuInsertarCompaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInsertarCompaniaActionPerformed
        if (insertarCompania == null || insertarCompania.isClosed()) {
            insertarCompania = new InsertarCompania();
            escritorio.add(insertarCompania);
            insertarCompania.setVisible(true);
        }
    }//GEN-LAST:event_menuInsertarCompaniaActionPerformed

    private void menuActualizarCompaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizarCompaActionPerformed
        if (actualizarCompania == null || actualizarCompania.isClosed()) {
            actualizarCompania = new ActualizarCompania();
            escritorio.add(actualizarCompania);
            actualizarCompania.setVisible(true);
        }
    }//GEN-LAST:event_menuActualizarCompaActionPerformed

    private void ArtistaConsultarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArtistaConsultarTodosActionPerformed
      if (formularioConsultaTodosArtistas == null || formularioConsultaTodosArtistas.isClosed()) {
            formularioConsultaTodosArtistas = new ConsultarTodosArtistas() ;
            escritorio.add(formularioConsultaTodosArtistas);
            formularioConsultaTodosArtistas.setVisible(true);
        }
    }//GEN-LAST:event_ArtistaConsultarTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Artista;
    private javax.swing.JMenuItem ArtistaConsultarTodos;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuActualizarCompa;
    private javax.swing.JMenu menuActualizarCompania;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuConsultarTodos;
    private javax.swing.JMenuItem menuConsultarUno;
    private javax.swing.JMenuItem menuEliminarCompania;
    private javax.swing.JMenuItem menuInsertarCompania;
    // End of variables declaration//GEN-END:variables

    ConsultaCompania fomularioConsultaUno = null;
    ConsultaTodosCompanias formularioConsultaTodosCompanias = null;
    ConsultarTodosArtistas formularioConsultaTodosArtistas = null;
    EliminarCompania eliminarCompania = null;
    InsertarCompania insertarCompania = null;
    ActualizarCompania actualizarCompania = null;
}
